import { useNavigate } from "react-router";
import { Save, Sparkles } from "lucide-react";
import { PageHeader } from "../../../components/ui/page-header";
import { useToast } from "../../../components/ui/toast";
import { useAuth } from "../../../auth/AuthProvider";
import { toMessage } from "../../../lib/errors";
import { automationApi, AutomationRuleInput } from "../api";
import { AutomationRuleComposer, createDefaultRuleDraft } from "../components/rule-composer";
import { useAutomationMutations } from "../hooks";

export function AutomationPlaygroundPage() {
  const navigate = useNavigate();
  const { session } = useAuth();
  const { notify } = useToast();
  const mutations = useAutomationMutations();

  async function saveRule(input: AutomationRuleInput) {
    try {
      const rule = await mutations.create.mutateAsync(input);
      notify("Rule saved from playground");
      navigate(`/app/automation/${rule.id}`);
    } catch (error) {
      notify("Save failed", toMessage(error));
      throw error;
    }
  }

  async function dryRun(input: AutomationRuleInput, payload: Record<string, unknown>) {
    let tempRuleId: string | undefined;
    try {
      const tempRule = await mutations.create.mutateAsync({
        ...input,
        name: `${input.name} dry-run`,
        description: "Temporary rule generated by automation playground dry-run."
      });
      tempRuleId = tempRule.id;
      const result = await automationApi.dryRun(session!, tempRule.id, payload);
      notify("Dry-run result", result.matched ? "MATCHED" : "NOT MATCHED");
      return result.matched;
    } catch (error) {
      notify("Dry-run failed", toMessage(error));
      throw error;
    } finally {
      if (tempRuleId) {
        await automationApi.delete(session!, tempRuleId).catch(() => undefined);
      }
    }
  }

  return (
    <>
      <PageHeader
        eyebrow="Automation playground"
        title="Build a readable workflow"
        description="Describe the rule as When, If and Then. InsightFlow generates the backend DSL and renders the workflow chart from that sentence."
      />
      <AutomationRuleComposer
        initialDraft={createDefaultRuleDraft()}
        submitLabel="Save workflow"
        submitIcon={<Save size={16} />}
        onSubmit={(input) => saveRule(input)}
        onDryRun={(input, payload) => dryRun(input, payload)}
        secondaryAction={<span className="inline-flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm font-semibold text-amber-800"><Sparkles size={16} /> Guided mode</span>}
      />
    </>
  );
}
